server:
  port: 6002

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/rate_my_hotel_db
    username: root
    password: root@2312
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    livereload:
      enabled: true

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:6001/eureka/
    enabled: true